### ISSUE TITLE
Timepicker not working in availability booking

### ISSUE THREAD

**Issue by plapornik** [jackstenglein/chess-dojo-scheduler#10]
Somewhere in the last couple of builds the time picker no longer does anything when you click on it in. This is when you try to add availability. I noticed someone has created multiple 1 hour slots. You can still manually enter the time; although I had issues choosing an end time after midnight.

**Comment by jackstenglein** [comment]
Thanks for reporting this! 

The time picker should display again now. The issue with end times after midnight is being tracked in #4
