### ISSUE TITLE
Handle multiple date formats for lichess study import

### ISSUE THREAD

**Issue by clarkevandenhoven** [jackstenglein/chess-dojo-scheduler#216]
It's annoying that every time I import from a lichess study chapter that I need my date tag in exactly the awkward `YYYY.MM.DD` format. We should allow other formats to be loaded in as valid dates.

**Comment by jackstenglein** [comment]
I've added a popup that prompts the user for the date if it is missing or in the wrong format, so I think this is no longer necessary.
