### ISSUE TITLE
Feature request: enable gradient colour scheme not just dark mode

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#348]
It would be nice if there was a gradient colour scheme like this, I know it be a lot of work but makes it more user-friendly 
![Screen Shot 2023-10-27 at 9 05 07 AM](https://github.com/jackstenglein/chess-dojo-scheduler/assets/92553013/4c43cdc7-1ee0-4bf5-b741-441f4b20a0b5)

**Comment by jackstenglein** [comment]
What are you wanting that to do? Change the background color to that gradient?

**Comment by jalpp** [comment]
yea have it changed to that gradient
