### ISSUE TITLE
Add API to fetch scoreboard data

### ISSUE THREAD

**Issue by jackstenglein** [jackstenglein/chess-dojo-scheduler#43]

**Comment by rmccarth** [comment]
I need some clarity on the difference between the scoreboard and tracking ones progress through their objectives/requirements. Is the idea to rank folks amongst cohort peers?

**Comment by jackstenglein** [comment]
The scoreboard is supposed to compile all users in a cohort and display each of their progressions in a table, similar to what the current google sheet is doing. I was planning to use MUI data grid for this
