### ISSUE TITLE
Enable unauthenticated users to view games

### ISSUE THREAD

**Issue by jackstenglein** [jackstenglein/chess-dojo-scheduler#467]
We want to allow people in the Dojo to share their annotations with people outside the Dojo, without those outside the Dojo having to sign up to view them.

Unauthenticated users should be able to view the game page, see all comments, look at the explorer on the game page, etc. However, they should not be able to post comments and if they try to click the "View all games in this position" button in the explorer, then they should be prompted to log in on the new tab that opens.

**Comment by chao-mu** [comment]
Is the permissions model here "anyone with the link has read only access"?

Is this a separate visibility the user sets or all "public" ones? 

What's the deal about discoverability? Should unauthenticated users be able to view/search for public games? If so, that seems like a stretch item.

**Comment by jackstenglein** [comment]
Yes, anyone who has the link should have access to that page. This should happen for any public or unlisted game.

Unauthenticated users should not be able to view the game list page. If they try, they should get redirected to the sign in page (which is what currently happens)

**Comment by chao-mu** [comment]
Should this be closed now that it's merged?

**Comment by jackstenglein** [comment]
Closed in #470
