### ISSUE TITLE
Support for 3D pieces custom piece styles, custom board colours and the colorful world

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#478]
I like playing in 3D chess mode and it just gives a better view for those who are OTB players might even help them, also the board colours/and 2d piece sets should be changeable to make it as user-friendly as possible.

**Comment by jackstenglein** [comment]
You're welcome to submit a PR, but otherwise this is pretty low priority for us, so it'll probably take a while for me to get to it

**Comment by jalpp** [comment]
as you say boss, expect a PR

**Comment by jackstenglein** [comment]
Closed in #480
