### ISSUE TITLE
Better UI for material tabs and in page designs 

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#488]
Better UI for material tabs and in-page designs,

I have some ideas and small tweaks which I will work on and shoot a PR here

**Comment by jalpp** [comment]
can assign to me

**Comment by jackstenglein** [comment]
@jalpp Should this still be open or are the material pages good now?

**Comment by jalpp** [comment]
> @jalpp Should this still be open or are the material pages good now?

still in works

**Comment by jalpp** [comment]
Overall almost all UI/UX parts are done on the main areas of the site, so closing this but general improvements be filled in different issue
