### ISSUE TITLE
Dojo Grad animation

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#503]
Dojo Grad animation todos goes here

**Comment by chao-mu** [comment]
@jalpp can you edit the description to include what problem/need/desire you are trying to solve and a rough description of your planned solution? FYI, I'm working on the grad badge stuff so we should coordinate efforts.

**Comment by jalpp** [comment]
Yea I have something in mind but I will get to it after I get some other parts of UI done @chao-mu

**Comment by chao-mu** [comment]
Still please update the description with your thoughts.
