### ISSUE TITLE
Shareable Graduation Overview Image

### ISSUE THREAD

**Issue by chao-mu** [jackstenglein/chess-dojo-scheduler#508]
An image that can be shared with the user's friends on social media to celebrate their achievement.

Random side thoughts: For this to be maximally effective for marketing purpose, we should make sure we're leading their friends to the dojo site. Perhaps a summary page or some such of their achievements. I will consider this unconfirmed stretch.

**Comment by chao-mu** [comment]
Jack: Rating change (possibly in a graph), dojo points earned, hours logged
Kostya: I think it'd be cool if we had a similar box that one could "generate" to see their stats in the program

**Comment by jalpp** [comment]
Grad animation is related to this fyi

**Comment by chao-mu** [comment]
![image](https://github.com/jackstenglein/chess-dojo-scheduler/assets/629183/6ff8b1f8-4257-4eb9-9235-bcbf3c026ece)

Feedback:
* larger text
* different header text than "welcome..."
* graph alternatives as stretch item
* textured background
* listing page not in scope (may still use this for testing, can remove after)
* add dojoOrange from MUI palette 
* dojo logo

Notes: When the cohort was joined/graduated should be present on the graduation object

I plan on rendering styled DOM with MUI and using html-to-image to turn it into an image. https://www.npmjs.com/package/html-to-image

**Comment by modestprogress** [comment]
"so many grads they have to get split into two days. So those who grad into sub 1100 should be told about the Wednesday show, those above that about the Thursday show"

**Comment by modestprogress** [comment]
![image](https://github.com/jackstenglein/chess-dojo-scheduler/assets/120434611/d3f0f149-b1ca-451b-b888-7963d8115a61)

**Comment by modestprogress** [comment]
Redirecting to a new page is too jarring.

"How about this. We open it as a dialog to fit the current workflow and then we shove a link somewhere to this page somewhere out of the way. If the user wants to come back to this, then they can perhaps with some nudging"

**Comment by modestprogress** [comment]
"you should be able to use the timestamp feature to convert the show time to their local time"
