### ISSUE TITLE
Bug: Position Explorer FEN copy URL broken

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#549]
go here https://www.chessdojo.club/games/explorer?fen=
play some random opening like ruy lopez
copy the new fen to "copy url"

expected 
get the new URL

bug
got the same https://www.chessdojo.club/games/explorer?fen= back

**Comment by chao-mu** [comment]
@jalpp Did you work on this since?

**Comment by jalpp** [comment]
I think @jackstenglein already fixed it?!

**Comment by chao-mu** [comment]
Still broken.

**Comment by chao-mu** [comment]
So looks like FEN in URL is never updated.
