### ISSUE TITLE
Support for U1000 Classical chess league

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#554]
Dojoliga U1000 classical league is being awaited to be created and started yet the func is not supported on the scoreboard side

https://github.com/jalpp/DojoLiga/commit/f7b835f730aad1f6936cd1e66c9bd5f45980ad56 

this commit has all the information about it, I'm not sure clients want a leaderboard filter on the leaderboard

thanks,
jalpp

**Comment by chao-mu** [comment]
@jalpp Did anything come of this?

**Comment by jalpp** [comment]
I think the filter wasn't need it
