### ISSUE TITLE
Dojo Tactics UI WIP

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#555]
add better and cleaner input on Dojo Tactics, and clean up some styling issues

please assign me @jackstenglein

**Comment by jackstenglein** [comment]
1. At the top of the Material > Tests page, remove the graphs
2. On the Material > Tests page, remove the header `Attempt Test` and the border around it. Just have the buttons for each test.
3. On the Material > Tests page, get rid of Tactics Rubric header above the instructions

**Comment by jalpp** [comment]
the max meter rating should be the next rating + 100 points
