### ISSUE TITLE
Refactor exam related variables from Polgar -> Checkmate

### ISSUE THREAD

**Issue by chao-mu** [jackstenglein/chess-dojo-scheduler#559]
Currently there are lots of variable names referring to Polgar in the code base when what is meant is the checkmate test, which limits potential future scope, is counter to the naming in the exam index, and honestly makes me nervous from a rights perspective. 

I'm not currently taking on this work, but it's a good "first issue" or "sick in bed" thing.

NOTE! Enum *values* would be nice to change, as well as URLs. HOWEVER, enum value changes may effect backend/storage layer and may be out of scope for now. URLs (and I mostly mean /tests/polar) should have a backwards compatibility shim.

**Comment by jackstenglein** [comment]
I don't think this is necessary. It's pretty common for things in the backend to have a different name than what is displayed in the frontend, and it's probably not worth migrating all the exam related data for this
