### ISSUE TITLE
embed vids

### ISSUE THREAD

**Issue by jessekraai** [jackstenglein/chess-dojo-scheduler#585]
On our vids doc there are vids that have been done but not added to the site, EFCW and Dvoretsky atm. Ludwig's file has the raw takes meant for the site.

**Comment by jackstenglein** [comment]
Not sure what "Ludwig's file" refers to, but if you want to embed a video, you can paste the YouTube **EMBED** link or vimeo link into the Website Scoreboard Format doc:

![Screenshot 2024-06-19 at 1 32 44 PM](https://github.com/jackstenglein/chess-dojo-scheduler/assets/22841845/587169d8-d723-4379-a2fa-784a2033eefc)
