### ISSUE TITLE
vids for games to memorize

### ISSUE THREAD

**Issue by jessekraai** [jackstenglein/chess-dojo-scheduler#586]
on the vids page we also have a list of vids that have been done whose raw form should be added to the games to memorize section

**Comment by jackstenglein** [comment]
For the games to memorize, add a new task and paste the link into the videos column:

![Screenshot 2024-06-19 at 1 33 55 PM](https://github.com/jackstenglein/chess-dojo-scheduler/assets/22841845/69b4b513-efda-458e-9ebb-3dfeeca2568a)
