### ISSUE TITLE
Make Dojo FAQ More Visible

### ISSUE THREAD

**Issue by hellokostya** [jackstenglein/chess-dojo-scheduler#594]
Would put it under the "more" dropdown menu in the nav bar

https://www.chessdojo.shop/training-program-faq

Formatting should be improved, e.g. questions should be bolded/italicized and the answers should be concise/to the point.

**Comment by jackstenglein** [comment]
@hellokostya I added the FAQ to the [help page](https://www.chessdojo.club/help)
