### ISSUE TITLE
Remove grayscreen effect from "Choose Variation" prompt (game editor)

### ISSUE THREAD

**Issue by hellokostya** [jackstenglein/chess-dojo-scheduler#723]
It's hard to play through a game quickly that has a lot of notes, because of the constant grayscreen, can we remove that and just have the variation box pop up on the top right side of the notes? I think that's the best place for it because if someone is interested in the variations, they'll probably be looking at the right side of the screen

**Comment by jackstenglein** [comment]
@hellokostya How's this? Personally I think it makes it more difficult both to notice the dialog has popped up, and to read the notes when the dialog is there.

<img width="1714" alt="Screenshot 2024-08-23 at 5 25 37 PM" src="https://github.com/user-attachments/assets/304ce886-4f4f-4ae5-bc94-aa9ecf9ec9b1">

**Comment by jackstenglein** [comment]
<img width="1718" alt="Screenshot 2024-08-23 at 5 37 25 PM" src="https://github.com/user-attachments/assets/3042e5c9-0734-454c-82b6-f549ad745462">

**Comment by jackstenglein** [comment]
@hellokostya I'm pushing up the version in the second screenshot for now. Let me know if further updates are needed. If not, please close this.

**Comment by hellokostya** [comment]
@jackstenglein Looks good to me! Only issue with the variation box is while it's open, using the down arrow key to select a variation also scrolls the page down, which is a bit annoying

**Comment by jackstenglein** [comment]
@hellokostya What browser/OS are you using? I've tested with Chrome/Firefox on Mac and Chrome on Windows and the down arrow key doesn't scroll the page down when the variation dialog is open

**Comment by hellokostya** [comment]
Using Chrome on Windows 11, just checked and it's still doing it

**Comment by jackstenglein** [comment]
@hellokostya I pushed up a change which I think may have fixed that. Could you check again please?
