### ISSUE TITLE
Bug: unAuth users see logged in view of coach upcoming tab

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#790]
unauth users don't have access to their coaches because they need to sign up for it, The upcoming session is a bit confusing, we should say upgrade to book your next session

go here without login https://www.chessdojo.club/coaching
switch to upcoming session
"No available sessions found for your cohort" seeing this first time as new user feels a bit off

**Comment by jackstenglein** [comment]
This is because nobody is doing coaching sessions right now unfortunately
