### ISSUE TITLE
Sign in/Sign up page are a bit off

### ISSUE THREAD

**Issue by jalpp** [jackstenglein/chess-dojo-scheduler#796]
when toggling between the sign-in/out page the Google sign-in button is mismatched, also the button and the next above say "sign in, create account twice" useless repetition. Also the the sign-in button/sign-up button have a blue color which has no real value, rather that can be dojo orange with a focal point of users' attention. Also the ChessDojo training program should have the logo beside it, its really a plan text and way too simple right now.

**Comment by chao-mu** [comment]
Liking these tickets - good job. If you'd be willing, check at 360px resolution and create mobile UI/UX tickets and assign to me

**Comment by jalpp** [comment]
sure
