### ISSUE TITLE
Heatmap is blank for some users

### ISSUE THREAD

**Issue by jackstenglein** [jackstenglein/chess-dojo-scheduler#976]
**📓 Steps to reproduce:** 
  > step 1
step 2
step 3
step 4
🔨 Platform: chessdojo.club
📱 Device Type: Mobile
🌐 Browser Type: Chrome
👤 Author @:nmp
https://discord.com/channels/951958534113886238/1299913797045325957/

**Comment by jalpp** [comment]
this works! 🥳

**Comment by jackstenglein** [comment]
@jalpp Is it possible to get the text of the bug report submitted by the user into GitHub?
